services:
  my-postgres:
    image: postgres:15
    container_name: ah_toolcheck_db
    environment:
     - POSTGRES_DB=${DATABASE_NAME}
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - '7014:5432'
    volumes:
    - pg_data:/var/lib/postgresql/data
    networks:
    - ag

  web:
    build: .
    container_name: ah_toolcheck_web
    ports:
      - '8024:8000'
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - my-postgres
networks:
  ag:
    external: true

volumes:
  pg_data:
